SELECT
    VARCHAR_FORMAT(DTMOVIMENTO, 'YYYY-MM') AS MES,
    COUNT(*) AS REG,
    CAST(SUM(VALLIQUIDOESPERADO) AS NUMERIC(15,2)) AS VALOR,
    CAST(AVG(DAYS(CURRENT DATE) - DAYS(DTMOVIMENTO)) AS INTEGER) AS DIAS
FROM DBA.CLW_RETORNO_CONTAS_RECEBER
WHERE DTPAGAMENTOEFETIVADO IS NULL
GROUP BY VARCHAR_FORMAT(DTMOVIMENTO, 'YYYY-MM')
ORDER BY MES;
