SELECT
    COUNT(*) AS REG,
    SUM(CASE WHEN STATUS = 'VALORES_CORRETOS' THEN 1 ELSE 0 END) AS CORRETOS,
    CAST(SUM(VALLIQUIDOESPERADO) AS NUMERIC(15,2)) AS ESPERADO,
    CAST(SUM(VALLIQUIDOPAGO) AS NUMERIC(15,2)) AS PAGO
FROM DBA.CLW_RETORNO_CONTAS_RECEBER
WHERE DTMOVIMENTO >= ?;
