SELECT
    EB.IDCTABANCARIA,
    COALESCE(PC.CLASSIFICACAO, 'sem vinculo') AS CLASSIFICACAO,
    COALESCE(
        PC.DESCRCTACONTABIL,
        'Conta bancaria ' || CAST(EB.IDCTABANCARIA AS VARCHAR(10)) || ' - sem conta contabil vinculada'
    ) AS NOME,
    COUNT(*) AS REG,
    CAST(SUM(EB.VALORCREDITO) AS NUMERIC(15,2)) AS CRED,
    CAST(SUM(EB.VALORDEBITO) AS NUMERIC(15,2)) AS DEB
FROM DBA.EXTRATO_BANCARIO EB
LEFT JOIN DBA.CONTABIL_PLANO_CONTAS PC
    ON PC.IDCTABANCARIA = EB.IDCTABANCARIA AND PC.FLAGCTABANCARIA = 'T'
WHERE EB.FLAGCONCILIADO = 'F'
  AND EB.DTMOVIMENTO >= ?
GROUP BY EB.IDCTABANCARIA, PC.CLASSIFICACAO, PC.DESCRCTACONTABIL
ORDER BY CRED DESC;
