WITH ULTIMA_DATA AS (
    SELECT
        IDEMPRESA,
        IDCTACONTABIL,
        MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.CONTABIL_SALDO
    WHERE IDEMPRESA IN ({{FILIAIS}})
      AND DTMOVIMENTO <= ?
    GROUP BY IDEMPRESA, IDCTACONTABIL
)
SELECT
    CAST(SUM(CASE WHEN PC.CLASSIFICACAO LIKE '115%' THEN CS.VALSALDOATUAL ELSE 0 END) AS NUMERIC(15,2)) AS SALDO_EMITIDO,
    CAST(SUM(CASE WHEN PC.CLASSIFICACAO LIKE '212%' THEN CS.VALSALDOATUAL ELSE 0 END) AS NUMERIC(15,2)) AS SALDO_RECEBIDO
FROM DBA.CONTABIL_SALDO CS
INNER JOIN ULTIMA_DATA UD
    ON UD.IDEMPRESA = CS.IDEMPRESA
    AND UD.IDCTACONTABIL = CS.IDCTACONTABIL
    AND UD.DTMOVIMENTO = CS.DTMOVIMENTO
INNER JOIN DBA.CONTABIL_PLANO_CONTAS PC
    ON PC.IDCTACONTABIL = CS.IDCTACONTABIL
WHERE CS.IDEMPRESA IN ({{FILIAIS}})
  AND (PC.CLASSIFICACAO LIKE '115%' OR PC.CLASSIFICACAO LIKE '212%');
