SELECT
    VARCHAR_FORMAT(DTMOVIMENTO, 'YYYY-MM') AS MES,
    COUNT(*) AS REG,
    CAST(SUM(VALORCREDITO) AS NUMERIC(15,2)) AS CRED,
    CAST(SUM(VALORDEBITO) AS NUMERIC(15,2)) AS DEB
FROM DBA.EXTRATO_BANCARIO
WHERE FLAGCONCILIADO = 'F'
  AND DTMOVIMENTO >= ?
GROUP BY VARCHAR_FORMAT(DTMOVIMENTO, 'YYYY-MM')
ORDER BY MES;
