SELECT
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN FLAGCONCILIADO = 'T' THEN 1 ELSE 0 END) AS CONCILIADO,
    SUM(CASE WHEN FLAGCONCILIADO = 'F' THEN 1 ELSE 0 END) AS NAO_CONCILIADO,
    CAST(SUM(CASE WHEN FLAGCONCILIADO = 'F' THEN VALORCREDITO ELSE 0 END) AS NUMERIC(15,2)) AS CRED_NAO_CONCILIADO,
    CAST(SUM(CASE WHEN FLAGCONCILIADO = 'F' THEN VALORDEBITO ELSE 0 END) AS NUMERIC(15,2)) AS DEB_NAO_CONCILIADO
FROM DBA.EXTRATO_BANCARIO
WHERE DTMOVIMENTO >= ?;
