SELECT
    IDPLANILHA,
    MIN(DTMOVIMENTO) AS DTMOVIMENTO,
    COUNT(DISTINCT IDEMPRESA) AS N_EMPRESAS,
    MIN(IDEMPRESA) AS IDEMPRESA_REF,
    CAST(SUM(CASE WHEN TIPONATUREZALCTO = 'D' THEN VALLANCAMENTO ELSE -VALLANCAMENTO END) AS NUMERIC(15,2)) AS DIFERENCA
FROM DBA.CONTABIL_MOVIMENTO
WHERE DTMOVIMENTO BETWEEN ? AND ?
  AND IDEMPRESA IN ({{FILIAIS}})
GROUP BY IDPLANILHA
HAVING ABS(SUM(CASE WHEN TIPONATUREZALCTO = 'D' THEN VALLANCAMENTO ELSE -VALLANCAMENTO END)) > 0.005
ORDER BY ABS(DIFERENCA) DESC
FETCH FIRST 200 ROWS ONLY;
