WITH ULTIMA_DATA AS (
    SELECT
        IDEMPRESA,
        IDCTACONTABIL,
        MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.CONTABIL_SALDO
    WHERE IDEMPRESA IN ({{FILIAIS}})
      AND DTMOVIMENTO <= ?
    GROUP BY IDEMPRESA, IDCTACONTABIL
)
SELECT
    PC.CLASSIFICACAO,
    PC.DESCRCTACONTABIL,
    CS.IDEMPRESA,
    CAST(CS.VALSALDOATUAL AS NUMERIC(15,2)) AS SALDO,
    CS.DTMOVIMENTO
FROM DBA.CONTABIL_SALDO CS
INNER JOIN ULTIMA_DATA UD
    ON UD.IDEMPRESA = CS.IDEMPRESA
    AND UD.IDCTACONTABIL = CS.IDCTACONTABIL
    AND UD.DTMOVIMENTO = CS.DTMOVIMENTO
INNER JOIN DBA.CONTABIL_PLANO_CONTAS PC
    ON PC.IDCTACONTABIL = CS.IDCTACONTABIL
    AND PC.TIPOCTACONTABIL = 'A'
WHERE CS.IDEMPRESA IN ({{FILIAIS}})
  AND (UPPER(PC.DESCRCTACONTABIL) LIKE '%CLASSIFICAR%' OR UPPER(PC.DESCRCTACONTABIL) LIKE '%IDENTIFICAR%')
  AND CS.VALSALDOATUAL <> 0
ORDER BY PC.CLASSIFICACAO, CS.IDEMPRESA;
