SELECT
    CASE WHEN CP.FLAGBAIXADA = 'T' THEN 'Baixado' ELSE 'Em aberto' END AS ESTADO,
    CASE
        WHEN CP.DTVENCIMENTO < CURRENT DATE THEN 'Vencido'
        WHEN CP.DTVENCIMENTO <= CURRENT DATE + 90 DAYS THEN 'A vencer'
        ELSE 'Programado (> 90 dias)'
    END AS SITUACAO,
    COUNT(*) AS TITULOS,
    CAST(SUM(CP.VALTITULO) AS NUMERIC(15,2)) AS VALOR,
    CAST(SUM(CP.VALTITULO - COALESCE(CP.SUMVALPAGAMENTOTITULO, 0) - COALESCE(CP.SUMVALDESCCONCEDIDOTITULO, 0)) AS NUMERIC(15,2)) AS SALDO
FROM DBA.CONTAS_PAGAR CP
WHERE CP.IDEMPRESA IN ({{FILIAIS}})
GROUP BY
    CASE WHEN CP.FLAGBAIXADA = 'T' THEN 'Baixado' ELSE 'Em aberto' END,
    CASE
        WHEN CP.DTVENCIMENTO < CURRENT DATE THEN 'Vencido'
        WHEN CP.DTVENCIMENTO <= CURRENT DATE + 90 DAYS THEN 'A vencer'
        ELSE 'Programado (> 90 dias)'
    END
ORDER BY ESTADO, SITUACAO;
