WITH MOV AS (
    SELECT
        VARCHAR_FORMAT(CS.DTMOVIMENTO, 'YYYY-MM') AS MES,
        PC.CLASSIFICACAO,
        CS.VALDEBITO AS DEB,
        CS.VALCREDITO AS CRED
    FROM DBA.CONTABIL_SALDO CS
    INNER JOIN DBA.CONTABIL_PLANO_CONTAS PC
        ON PC.IDCTACONTABIL = CS.IDCTACONTABIL
    WHERE CS.IDEMPRESA IN ({{FILIAIS}})
      AND CS.DTMOVIMENTO BETWEEN ? AND ?
      AND PC.TIPOCTACONTABIL = 'A'
      AND (PC.CLASSIFICACAO LIKE '311%' OR PC.CLASSIFICACAO LIKE '312%'
           OR PC.CLASSIFICACAO LIKE '411%' OR PC.CLASSIFICACAO LIKE '421%')
)
SELECT
    MES,
    CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '31101%' OR CLASSIFICACAO LIKE '31102%' THEN CRED-DEB ELSE 0 END) AS NUMERIC(15,2)) AS RECEITA_BRUTA,
    CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '31103%' THEN CRED-DEB ELSE 0 END) AS NUMERIC(15,2)) AS DEDUCOES,
    CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '411%' THEN DEB-CRED ELSE 0 END) AS NUMERIC(15,2)) AS CMV,
    CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '421%' AND CLASSIFICACAO NOT LIKE '42105%' THEN DEB-CRED ELSE 0 END) AS NUMERIC(15,2)) AS DESPESAS_OPERACIONAIS,
    CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '31201%' THEN CRED-DEB ELSE 0 END) AS NUMERIC(15,2)) AS RECEITAS_FINANCEIRAS,
    CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '42105%' THEN DEB-CRED ELSE 0 END) AS NUMERIC(15,2)) AS DESPESAS_FINANCEIRAS
FROM MOV
GROUP BY MES
ORDER BY MES;
