SELECT
    COALESCE(PV.FABRICANTE, 'Sem fabricante') AS FABRICANTE,
    CAST(SUM(EA.QTDPRODUTO) AS NUMERIC(15, 2)) AS QUANTIDADE,
    CAST(SUM(EA.VALTOTLIQUIDO) AS NUMERIC(15, 2)) AS VALOR
FROM
    DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = EA.IDSUBPRODUTO
WHERE
    EA.IDOPERACAO IN (1089, 1092)
    AND EA.IDEMPRESA IN ({{FILIAIS}})
    AND EA.DTMOVIMENTO BETWEEN ? AND ?
GROUP BY
    PV.FABRICANTE
ORDER BY
    VALOR DESC;
