SELECT
    PV.IDSECAO,
    S.DESCRSECAO,
    CAST(SUM(EA.QTDPRODUTO) AS NUMERIC(15, 2)) AS QUANTIDADE,
    CAST(SUM(EA.VALTOTLIQUIDO) AS NUMERIC(15, 2)) AS VALOR
FROM
    DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = EA.IDSUBPRODUTO
    INNER JOIN DBA.SECAO S ON S.IDSECAO = PV.IDSECAO
WHERE
    EA.IDOPERACAO IN (1089, 1092)
    AND EA.IDEMPRESA IN ({{FILIAIS}})
    {{MERCADOLOGICO}}
    AND EA.DTMOVIMENTO BETWEEN ? AND ?
GROUP BY
    PV.IDSECAO, S.DESCRSECAO
ORDER BY
    S.DESCRSECAO;
