SELECT
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.IDCODBARPROD,
    PV.FABRICANTE,
    D.DESCRDIVISAO,
    S.DESCRSECAO,
    G.DESCRGRUPO,
    SG.DESCRSUBGRUPO,
    PV.FLAGINATIVO
FROM
    DBA.PRODUTOS_VIEW PV
    LEFT JOIN DBA.DIVISAO D ON D.IDDIVISAO = PV.IDDIVISAO
    LEFT JOIN DBA.SECAO S ON S.IDSECAO = PV.IDSECAO
    LEFT JOIN DBA.GRUPO G ON G.IDGRUPO = PV.IDGRUPO
    LEFT JOIN DBA.SUBGRUPO SG ON SG.IDSUBGRUPO = PV.IDSUBGRUPO
WHERE
    {{FILTROS}}
ORDER BY
    PV.DESCRICAOPRODUTO
FETCH FIRST 200 ROWS ONLY;
