SELECT
    C.IDEMPRESA,
    EM.NOMEFANTASIA AS NOME_EMPRESA,
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.IDCODBARPROD,
    C.DESCRICAOCONCORRENTE AS CONCORRENTE_NOME,
    CAST(CCP.VALPRECOVAREJOCONCORRENTE AS NUMERIC(15, 2)) AS PRECO_CONCORRENTE,
    CAST(TPP.VALPRECOVENDA AS NUMERIC(15, 2)) AS PRECO_NOSSO,
    CC.DTMOVIMENTO AS DATA_COTACAO
FROM
    DBA.COTACAO_CONCORRENCIA_PROD CCP
    INNER JOIN DBA.COTACAO_CONCORRENCIA CC ON CC.IDCOTACAO = CCP.IDCOTACAO
    INNER JOIN DBA.CONCORRENTE C ON C.IDCONCORRENTE = CCP.IDCONCORRENTE
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = CCP.IDSUBPRODUTO
    INNER JOIN DBA.EMPRESA EM ON EM.IDEMPRESA = C.IDEMPRESA
    LEFT JOIN DBA.TABELA_PRECO_PRODUTO TPP
        ON TPP.IDSUBPRODUTO = CCP.IDSUBPRODUTO
        AND TPP.IDEMPRESA = C.IDEMPRESA
        AND TPP.IDTABELAPRECO = 1
WHERE
    C.IDEMPRESA IN ({{FILIAIS}})
    {{FILTROS}}
ORDER BY
    CC.DTMOVIMENTO DESC
FETCH FIRST 300 ROWS ONLY;
