WITH VENDA_90D AS (
    SELECT
        EA.IDSUBPRODUTO,
        EA.IDEMPRESA,
        SUM(EA.QTDPRODUTO) AS QTD_VENDIDA
    FROM
        DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    WHERE
        OI.TIPOMOVIMENTO = 'V'
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
    GROUP BY
        EA.IDSUBPRODUTO, EA.IDEMPRESA
),
ULTIMA_DATA AS (
    SELECT IDEMPRESA, MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.ESTOQUE_SALDO_ATUAL
    WHERE IDEMPRESA IN ({{FILIAIS}})
        AND DTMOVIMENTO <= CURRENT DATE
    GROUP BY IDEMPRESA
)
SELECT
    ES.IDEMPRESA,
    EM.NOMEFANTASIA AS NOME_EMPRESA,
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.IDCODBARPROD,
    S.DESCRSECAO,
    CAST(ES.QTDATUALESTOQUE AS NUMERIC(15, 2)) AS QTDATUALESTOQUE,
    CAST(ES.VALATUALESTOQUE AS NUMERIC(15, 2)) AS VALATUALESTOQUE,
    CAST(V.QTD_VENDIDA AS NUMERIC(15, 2)) AS QTD_VENDIDA_90D,
    CAST((ES.QTDATUALESTOQUE / (V.QTD_VENDIDA / 90.0)) AS NUMERIC(15, 1)) AS DIAS_COBERTURA
FROM
    DBA.ESTOQUE_SALDO_ATUAL ES
    INNER JOIN ULTIMA_DATA UD ON UD.IDEMPRESA = ES.IDEMPRESA AND UD.DTMOVIMENTO = ES.DTMOVIMENTO
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = ES.IDSUBPRODUTO
    INNER JOIN DBA.SECAO S ON S.IDSECAO = PV.IDSECAO
    INNER JOIN DBA.EMPRESA EM ON EM.IDEMPRESA = ES.IDEMPRESA
    INNER JOIN VENDA_90D V ON V.IDSUBPRODUTO = ES.IDSUBPRODUTO AND V.IDEMPRESA = ES.IDEMPRESA
WHERE
    ES.IDEMPRESA IN ({{FILIAIS}})
    AND ES.QTDATUALESTOQUE > 0
    AND V.QTD_VENDIDA > 0
    {{MERCADOLOGICO}}
ORDER BY
    DIAS_COBERTURA ASC;
