WITH ULTIMA_DATA AS (
    SELECT
        IDEMPRESA,
        MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.ESTOQUE_SALDO_ATUAL
    WHERE IDEMPRESA IN ({{FILIAIS}})
        AND DTMOVIMENTO <= CURRENT DATE
    GROUP BY IDEMPRESA
)
SELECT
    PV.IDSECAO,
    S.DESCRSECAO,
    CAST(SUM(ES.VALATUALESTOQUE) AS NUMERIC(15, 2)) AS VALOR_ESTOQUE
FROM
    DBA.ESTOQUE_SALDO_ATUAL ES
    INNER JOIN ULTIMA_DATA UD
        ON UD.IDEMPRESA = ES.IDEMPRESA
        AND UD.DTMOVIMENTO = ES.DTMOVIMENTO
    INNER JOIN DBA.PRODUTOS_VIEW PV
        ON PV.IDSUBPRODUTO = ES.IDSUBPRODUTO
    INNER JOIN DBA.SECAO S
        ON S.IDSECAO = PV.IDSECAO
WHERE
    ES.IDEMPRESA IN ({{FILIAIS}})
GROUP BY
    PV.IDSECAO, S.DESCRSECAO
ORDER BY
    S.DESCRSECAO;
