WITH ULTIMA_DATA AS (
    SELECT IDEMPRESA, MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.ESTOQUE_SALDO_ATUAL
    WHERE IDEMPRESA IN ({{FILIAIS}})
        AND DTMOVIMENTO <= CURRENT DATE
    GROUP BY IDEMPRESA
)
SELECT
    PV.IDSUBPRODUTO,
    CAST(SUM(ES.VALATUALESTOQUE) AS NUMERIC(15, 2)) AS VALOR_ESTOQUE
FROM
    DBA.ESTOQUE_SALDO_ATUAL ES
    INNER JOIN ULTIMA_DATA UD ON UD.IDEMPRESA = ES.IDEMPRESA AND UD.DTMOVIMENTO = ES.DTMOVIMENTO
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = ES.IDSUBPRODUTO
WHERE
    ES.IDEMPRESA IN ({{FILIAIS}})
    AND UPPER(PV.FABRICANTE) = UPPER(?)
GROUP BY
    PV.IDSUBPRODUTO;
