SELECT
    CF.IDCLIFOR,
    CF.NOME,
    CF.NOMEFANTASIA,
    CF.CNPJCPF,
    CF.EMAIL,
    CF.FONE1,
    CF.FONE2,
    CF.FONECELULAR,
    CF.NOMECONTATO1,
    CF.NOMECONTATO2,
    CF.ENDERECO,
    CF.BAIRRO,
    CF.UFCLIFOR,
    CF.FLAGINATIVO
FROM
    DBA.CLIENTE_FORNECEDOR CF
WHERE
    CF.TIPOCADASTRO IN ('F', 'A')
    AND (UPPER(CF.NOME) LIKE UPPER(?) OR UPPER(CF.NOMEFANTASIA) LIKE UPPER(?) OR CF.CNPJCPF LIKE ?)
ORDER BY
    CF.FLAGINATIVO, CF.NOME
FETCH FIRST 50 ROWS ONLY;
