SELECT
    CF.IDCLIFOR,
    CF.NOME,
    CF.NOMEFANTASIA,
    CF.CNPJCPF,
    CF.EMAIL,
    CF.FONE1,
    CF.FONE2,
    CF.FONECELULAR,
    CF.NOMECONTATO1,
    CF.NOMECONTATO2,
    CF.ENDERECO,
    CF.BAIRRO,
    CF.UFCLIFOR,
    CF.FLAGINATIVO
FROM
    DBA.CLIENTE_FORNECEDOR CF
WHERE
    CF.IDCLIFOR IN ({{IDS}});
