SELECT DISTINCT
    PV.IDDIVISAO,
    D.DESCRDIVISAO,
    PV.IDSECAO,
    S.DESCRSECAO,
    PV.IDGRUPO,
    G.DESCRGRUPO
FROM
    DBA.PRODUTOS_VIEW PV
    LEFT JOIN DBA.DIVISAO D ON D.IDDIVISAO = PV.IDDIVISAO
    LEFT JOIN DBA.SECAO S ON S.IDSECAO = PV.IDSECAO
    LEFT JOIN DBA.GRUPO G ON G.IDGRUPO = PV.IDGRUPO
WHERE
    PV.IDSECAO IS NOT NULL
ORDER BY
    D.DESCRDIVISAO, S.DESCRSECAO, G.DESCRGRUPO;
