SELECT
    CF.NOME AS FORNECEDOR,
    COUNT(DISTINCT PC.IDPEDIDO) AS QTD_PEDIDOS,
    CAST(SUM(
        (PCP.QTDSOLICITADA - COALESCE(PCP.QTDATENDIDA, 0) - COALESCE(PCP.QTDCANCELADA, 0)) * PCP.VALUNITARIO
    ) AS NUMERIC(15, 2)) AS VALOR_PENDENTE
FROM
    DBA.PEDIDO_COMPRA PC
    INNER JOIN DBA.PEDIDO_COMPRA_PROD PCP
        ON PCP.IDEMPRESA = PC.IDEMPRESA
        AND PCP.IDPEDIDO = PC.IDPEDIDO
        AND PCP.IDCLIFOR = PC.IDCLIFOR
    INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = PC.IDCLIFOR
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = PCP.IDSUBPRODUTO
WHERE
    PC.FLAGCANCELADO = 'F'
    AND PC.IDEMPRESA IN ({{FILIAIS}})
    AND (PCP.QTDSOLICITADA - COALESCE(PCP.QTDATENDIDA, 0) - COALESCE(PCP.QTDCANCELADA, 0)) > 0
    {{MERCADOLOGICO}}
GROUP BY
    CF.NOME
ORDER BY
    VALOR_PENDENTE DESC;
