WITH PERDAS AS (
    SELECT
        EA.IDSUBPRODUTO,
        SUM(EA.QTDPRODUTO) AS QTD,
        SUM(EA.VALTOTLIQUIDO) AS VALOR
    FROM DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = EA.IDSUBPRODUTO
    WHERE
        EA.IDOPERACAO IN (1091, 1082, 1084, 1284, 1089, 1092)
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
        {{MERCADOLOGICO}}
    GROUP BY EA.IDSUBPRODUTO
),
ULTIMA_COMPRA AS (
    SELECT
        C.IDSUBPRODUTO,
        N.IDCLIFOR,
        ROW_NUMBER() OVER (PARTITION BY C.IDSUBPRODUTO ORDER BY C.DTMOVIMENTO DESC) AS RN
    FROM DBA.ESTOQUE_ANALITICO C
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = C.IDOPERACAO
        INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = C.IDEMPRESA AND N.IDPLANILHA = C.IDPLANILHA
    WHERE
        OI.TIPOMOVIMENTO = 'C'
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND C.IDSUBPRODUTO IN (SELECT IDSUBPRODUTO FROM PERDAS)
        AND C.DTMOVIMENTO >= CURRENT DATE - 365 DAYS
)
SELECT
    COALESCE(CF.NOME, 'Sem fornecedor identificado') AS FORNECEDOR,
    CAST(SUM(P.QTD) AS NUMERIC(15, 2)) AS QUANTIDADE,
    CAST(SUM(P.VALOR) AS NUMERIC(15, 2)) AS VALOR
FROM PERDAS P
    LEFT JOIN ULTIMA_COMPRA UC ON UC.IDSUBPRODUTO = P.IDSUBPRODUTO AND UC.RN = 1
    LEFT JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = UC.IDCLIFOR
GROUP BY
    CF.NOME
ORDER BY
    VALOR DESC;
