WITH ULTIMA_COMPRA AS (
    SELECT
        EA.IDEMPRESA,
        MAX(EA.DTMOVIMENTO) AS DTULTIMACOMPRA
    FROM
        DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    WHERE
        EA.IDSUBPRODUTO = ?
        AND OI.TIPOMOVIMENTO = 'C'
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND EA.IDEMPRESA IN (1, 2, 3, 4)
    GROUP BY
        EA.IDEMPRESA
)
SELECT
    EA.IDEMPRESA,
    UC.DTULTIMACOMPRA,
    CAST(MAX(EA.VALUNITBRUTO) AS NUMERIC(15, 4)) AS VALCUSTOULTIMO
FROM
    DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    INNER JOIN ULTIMA_COMPRA UC ON UC.IDEMPRESA = EA.IDEMPRESA AND UC.DTULTIMACOMPRA = EA.DTMOVIMENTO
WHERE
    EA.IDSUBPRODUTO = ?
    AND OI.TIPOMOVIMENTO = 'C'
    AND OI.FLAGMOVPRODUTOS = 'T'
    AND EA.IDEMPRESA IN (1, 2, 3, 4)
GROUP BY
    EA.IDEMPRESA, UC.DTULTIMACOMPRA
ORDER BY
    EA.IDEMPRESA;
