WITH ULTIMA_DATA AS (
    SELECT IDEMPRESA, MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.ESTOQUE_SALDO_ATUAL
    WHERE IDEMPRESA IN ({{FILIAIS}})
        AND DTMOVIMENTO <= CURRENT DATE
    GROUP BY IDEMPRESA
),
ULTIMA_COMPRA AS (
    SELECT
        EA.IDSUBPRODUTO,
        EA.IDEMPRESA,
        MAX(EA.DTMOVIMENTO) AS DTULTIMACOMPRA
    FROM
        DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    WHERE
        OI.TIPOMOVIMENTO = 'C'
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND EA.IDEMPRESA IN ({{FILIAIS}})
    GROUP BY
        EA.IDSUBPRODUTO, EA.IDEMPRESA
)
SELECT
    ES.IDEMPRESA,
    EM.NOMEFANTASIA AS NOME_EMPRESA,
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.IDCODBARPROD,
    D.DESCRDIVISAO,
    S.DESCRSECAO,
    CAST(ES.QTDATUALESTOQUE AS NUMERIC(15, 2)) AS QTDATUALESTOQUE,
    CAST(ES.VALATUALESTOQUE AS NUMERIC(15, 2)) AS VALATUALESTOQUE,
    ES.DTULTIMAVENDA,
    UC.DTULTIMACOMPRA
FROM
    DBA.ESTOQUE_SALDO_ATUAL ES
    INNER JOIN ULTIMA_DATA UD ON UD.IDEMPRESA = ES.IDEMPRESA AND UD.DTMOVIMENTO = ES.DTMOVIMENTO
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = ES.IDSUBPRODUTO
    INNER JOIN DBA.DIVISAO D ON D.IDDIVISAO = PV.IDDIVISAO
    INNER JOIN DBA.SECAO S ON S.IDSECAO = PV.IDSECAO
    INNER JOIN DBA.EMPRESA EM ON EM.IDEMPRESA = ES.IDEMPRESA
    LEFT JOIN ULTIMA_COMPRA UC ON UC.IDSUBPRODUTO = ES.IDSUBPRODUTO AND UC.IDEMPRESA = ES.IDEMPRESA
WHERE
    ES.IDEMPRESA IN ({{FILIAIS}})
    AND ES.QTDATUALESTOQUE > 0
    AND PV.FLAGINATIVO = 'F'
    AND (ES.DTULTIMAVENDA IS NULL OR ES.DTULTIMAVENDA < CURRENT DATE - ? DAYS)
    AND (UC.DTULTIMACOMPRA IS NULL OR UC.DTULTIMACOMPRA < CURRENT DATE - ? DAYS)
    {{EXCLUSAO_CATEGORIAS}}
ORDER BY
    ES.VALATUALESTOQUE DESC
FETCH FIRST 200 ROWS ONLY;
