WITH RANKED AS (
    SELECT
        NV.IDEMPRESA,
        NV.DTVALIDADE,
        NV.QTDPRODUTO,
        ROW_NUMBER() OVER (PARTITION BY NV.IDEMPRESA ORDER BY NV.DTVALIDADE ASC) AS RN
    FROM
        DBA.NOTAS_VALIDADE NV
    WHERE
        NV.IDSUBPRODUTO = ?
        AND NV.DTVALIDADE < DATE('2100-01-01')
        AND NV.DTVALIDADE >= CURRENT DATE
)
SELECT
    IDEMPRESA,
    DTVALIDADE,
    CAST(QTDPRODUTO AS NUMERIC(12, 2)) AS QTDPRODUTO
FROM
    RANKED
WHERE
    RN = 1
ORDER BY
    DTVALIDADE ASC;
