SELECT
    PTV.IDEMPRESA,
    PTV.UFORIGEM,
    PTV.PERICMSAI,
    PTV.PERICMSUBST,
    ST.DESCRSITTRIBUTARIA
FROM
    DBA.PRODUTO_TRIBUTACAO_VIEW PTV
    LEFT JOIN DBA.SITUACAO_TRIBUTARIA ST ON ST.IDSITTRIBUTARIA = PTV.IDSITTRIBSAI
WHERE
    PTV.IDSUBPRODUTO = ?
ORDER BY
    PTV.IDEMPRESA;
