SELECT
    PGE.IDEMPRESA,
    EM.NOMEFANTASIA AS NOME_EMPRESA
FROM
    DBA.PROMOCAO_GESTAO_EMPRESA PGE
    INNER JOIN DBA.EMPRESA EM ON EM.IDEMPRESA = PGE.IDEMPRESA
WHERE
    PGE.IDPROMOCAO = ?
    AND PGE.FLAGINATIVO = 'F'
ORDER BY
    EM.NOMEFANTASIA;
