SELECT
    PV.IDDIVISAO,
    D.DESCRDIVISAO,
    PV.IDSECAO,
    S.DESCRSECAO,
    PV.IDGRUPO,
    G.DESCRGRUPO,
    PV.IDSUBGRUPO,
    SG.DESCRSUBGRUPO,
    SUM(CASE WHEN PV.FLAGINATIVO = 'F' THEN 1 ELSE 0 END) AS ATIVOS,
    SUM(CASE WHEN PV.FLAGINATIVO = 'T' THEN 1 ELSE 0 END) AS INATIVOS,
    COUNT(*) AS TOTAL
FROM
    DBA.PRODUTOS_VIEW PV
    LEFT JOIN DBA.DIVISAO D ON D.IDDIVISAO = PV.IDDIVISAO
    LEFT JOIN DBA.SECAO S ON S.IDSECAO = PV.IDSECAO
    LEFT JOIN DBA.GRUPO G ON G.IDGRUPO = PV.IDGRUPO
    LEFT JOIN DBA.SUBGRUPO SG ON SG.IDSUBGRUPO = PV.IDSUBGRUPO
GROUP BY
    PV.IDDIVISAO, D.DESCRDIVISAO,
    PV.IDSECAO, S.DESCRSECAO,
    PV.IDGRUPO, G.DESCRGRUPO,
    PV.IDSUBGRUPO, SG.DESCRSUBGRUPO
ORDER BY
    D.DESCRDIVISAO, S.DESCRSECAO, G.DESCRGRUPO, SG.DESCRSUBGRUPO;
