SELECT
    S.IDSECAO,
    S.DESCRSECAO,
    SUM(CASE WHEN PV.FLAGINATIVO = 'F' THEN 1 ELSE 0 END) AS ATIVOS,
    SUM(CASE WHEN PV.FLAGINATIVO = 'T' THEN 1 ELSE 0 END) AS INATIVOS,
    COUNT(*) AS TOTAL
FROM
    DBA.PRODUTOS_VIEW PV
    INNER JOIN DBA.SECAO S ON S.IDSECAO = PV.IDSECAO
GROUP BY
    S.IDSECAO, S.DESCRSECAO
ORDER BY
    TOTAL DESC;
