WITH TICKETS AS (
    SELECT
        EA.IDEMPRESA,
        EA.IDPLANILHA,
        N.IDUSUARIO,
        SUM(
            CASE
                WHEN COALESCE(EA.NUMSEQUENCIAKIT, 0) <= 0 AND OI.TIPOMOVIMENTO = 'V'
                    THEN COALESCE(EA.VALLUCRO, 0) * EA.QTDPRODUTO
                ELSE 0
            END
        ) AS LUCRO_NOTA
    FROM
        DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
            ON NES.IDEMPRESA = EA.IDEMPRESA
            AND NES.IDPLANILHA = EA.IDPLANILHA
            AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
        INNER JOIN DBA.NOTAS N
            ON N.IDEMPRESA = EA.IDEMPRESA
            AND N.IDPLANILHA = EA.IDPLANILHA
            AND N.FLAGNOTACANCEL = 'F'
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    WHERE
        OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO = 'V'
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.IDOPERACAO <> 1301
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
    GROUP BY
        EA.IDEMPRESA, EA.IDPLANILHA, N.IDUSUARIO
)
SELECT
    U.IDUSUARIO,
    COALESCE(U.NOMESOBRENOME, U.NOMEUSUARIO) AS NOME_OPERADOR,
    SUM(CASE WHEN LUCRO_NOTA > 0 THEN 1 ELSE 0 END) AS TICKETS_POSITIVOS,
    SUM(CASE WHEN LUCRO_NOTA <= 0 THEN 1 ELSE 0 END) AS TICKETS_NEGATIVOS,
    COUNT(*) AS TOTAL_TICKETS
FROM
    TICKETS T
    INNER JOIN DBA.USUARIO U ON U.IDUSUARIO = T.IDUSUARIO
GROUP BY
    U.IDUSUARIO, COALESCE(U.NOMESOBRENOME, U.NOMEUSUARIO)
ORDER BY
    TOTAL_TICKETS DESC;
