WITH TICKETS AS (
    SELECT DISTINCT
        EA.IDEMPRESA,
        EA.IDPLANILHA,
        N.IDUSUARIO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
            ON NES.IDEMPRESA = EA.IDEMPRESA
            AND NES.IDPLANILHA = EA.IDPLANILHA
            AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
        INNER JOIN DBA.NOTAS N
            ON N.IDEMPRESA = EA.IDEMPRESA
            AND N.IDPLANILHA = EA.IDPLANILHA
            AND N.FLAGNOTACANCEL = 'F'
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    WHERE
        OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO = 'V'
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.IDOPERACAO <> 1301
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND {{ECOMMERCE}}
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
),
TICKETS_CLASSIFICADOS AS (
    SELECT
        T.IDEMPRESA,
        T.IDPLANILHA,
        T.IDUSUARIO,
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM DBA.VENDA_IDENTIFICADA_CLUBE_BENEFICIO VICB
                WHERE VICB.IDEMPRESA = T.IDEMPRESA
                    AND VICB.IDPLANILHA = T.IDPLANILHA
            ) THEN 1
            ELSE 0
        END AS FLAGCLIENTEIDENTIFICADO
    FROM
        TICKETS T
)
SELECT
    U.IDUSUARIO,
    COALESCE(U.NOMESOBRENOME, U.NOMEUSUARIO) AS NOME_OPERADOR,
    SUM(FLAGCLIENTEIDENTIFICADO) AS TICKETS_POSITIVOS,
    SUM(1 - FLAGCLIENTEIDENTIFICADO) AS TICKETS_NEGATIVOS,
    COUNT(*) AS TOTAL_TICKETS
FROM
    TICKETS_CLASSIFICADOS TC
    INNER JOIN DBA.USUARIO U ON U.IDUSUARIO = TC.IDUSUARIO
GROUP BY
    U.IDUSUARIO, COALESCE(U.NOMESOBRENOME, U.NOMEUSUARIO)
ORDER BY
    TOTAL_TICKETS DESC;
