SELECT
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.FABRICANTE,
    PV.NCM,
    PTV.IDEMPRESA,
    PTV.UFORIGEM,
    PTV.PERICMSAI,
    PTV.PERICMSUBST,
    ST.DESCRSITTRIBUTARIA
FROM
    DBA.PRODUTOS_VIEW PV
    INNER JOIN DBA.PRODUTO_TRIBUTACAO_VIEW PTV ON PTV.IDSUBPRODUTO = PV.IDSUBPRODUTO
    LEFT JOIN DBA.SITUACAO_TRIBUTARIA ST ON ST.IDSITTRIBUTARIA = PTV.IDSITTRIBSAI
WHERE
    UPPER(PV.DESCRICAOPRODUTO) LIKE UPPER(?)
ORDER BY
    PV.DESCRICAOPRODUTO, PTV.IDEMPRESA
FETCH FIRST 50 ROWS ONLY;
