SELECT
    NV.IDEMPRESA,
    EM.NOMEFANTASIA AS NOME_EMPRESA,
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.IDCODBARPROD,
    NES.DTMOVIMENTO AS DTLANCAMENTO,
    NV.DTVALIDADE,
    CAST(NV.QTDPRODUTO AS NUMERIC(12, 2)) AS QTDPRODUTO,
    NV.STATUS,
    NV.OBSERVACAO,
    CAST(NV.PRECOSUGERIDO AS NUMERIC(15, 2)) AS PRECOSUGERIDO,
    CAST(NV.QTDPRODUTO * COALESCE(TPP.VALPRECOVENDA, 0) AS NUMERIC(15, 2)) AS VALOR_ESTIMADO
FROM
    DBA.NOTAS_VALIDADE NV
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = NV.IDSUBPRODUTO
    INNER JOIN DBA.EMPRESA EM ON EM.IDEMPRESA = NV.IDEMPRESA
    LEFT JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDEMPRESA = NV.IDEMPRESA AND NES.IDPLANILHA = NV.IDPLANILHA
    LEFT JOIN DBA.TABELA_PRECO_PRODUTO TPP
        ON TPP.IDSUBPRODUTO = NV.IDSUBPRODUTO
        AND TPP.IDEMPRESA = NV.IDEMPRESA
        AND TPP.IDTABELAPRECO = 1
WHERE
    NV.IDEMPRESA IN ({{FILIAIS}})
    AND NV.DTVALIDADE < DATE('2100-01-01')
    {{FILTROS}}
ORDER BY
    NV.DTVALIDADE ASC
FETCH FIRST 300 ROWS ONLY;
