WITH BASE AS (
    SELECT
        EA.DTMOVIMENTO,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT, 0) <= 0 AND OI.TIPOMOVIMENTO = 'V' AND {{ECOMMERCE}}
                THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALVENDA,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT, 0) <= 0 AND OI.TIPOMOVIMENTO = 'V' AND {{ECOMMERCE}}
                THEN COALESCE(EA.VALLUCRO, 0) * EA.QTDPRODUTO
            ELSE 0
        END AS VALLUCRO,
        CASE
            WHEN OI.TIPOMOVIMENTO = 'C'
                THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALCOMPRA
    FROM
        DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
            ON NES.IDEMPRESA = EA.IDEMPRESA
            AND NES.IDPLANILHA = EA.IDPLANILHA
            AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
        INNER JOIN DBA.OPERACAO_INTERNA OI
            ON OI.IDOPERACAO = EA.IDOPERACAO
        INNER JOIN DBA.PRODUTOS_VIEW PV
            ON PV.IDSUBPRODUTO = EA.IDSUBPRODUTO
    WHERE
        OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO IN ('V', 'C')
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.IDOPERACAO <> 1301
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        {{MERCADOLOGICO}}
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
)
SELECT
    DTMOVIMENTO,
    CAST(SUM(VALVENDA) AS NUMERIC(15, 2)) AS VENDA,
    CAST(SUM(VALLUCRO) AS NUMERIC(15, 2)) AS LUCRO,
    CAST(SUM(VALCOMPRA) AS NUMERIC(15, 2)) AS COMPRA
FROM
    BASE
GROUP BY
    DTMOVIMENTO
ORDER BY
    DTMOVIMENTO;
