WITH BASE AS (
    SELECT
        CASE
            WHEN EA.IDVENDEDOR IN (3529, 3490, 3491, 3530, 8904, 134277) THEN 99
            ELSE E.IDEMPRESA
        END AS IDEMPRESA,
        CASE
            WHEN EA.IDVENDEDOR IN (3529, 3490, 3491, 3530, 8904, 134277) THEN 'E-COMMERCE'
            ELSE E.NOMEFANTASIA
        END AS NOME_EMPRESA,
        PV.IDSECAO,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT, 0) <= 0 AND OI.TIPOMOVIMENTO = 'V'
                THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALVENDA,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT, 0) <= 0 AND OI.TIPOMOVIMENTO = 'V'
                THEN COALESCE(EA.VALLUCRO, 0) * EA.QTDPRODUTO
            ELSE 0
        END AS VALLUCRO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.PRODUTOS_VIEW PV
            ON PV.IDSUBPRODUTO = EA.IDSUBPRODUTO
        INNER JOIN DBA.EMPRESA E
            ON E.IDEMPRESA = EA.IDEMPRESA
        INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
            ON NES.IDEMPRESA = EA.IDEMPRESA
            AND NES.IDPLANILHA = EA.IDPLANILHA
            AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
        INNER JOIN DBA.OPERACAO_INTERNA OI
            ON OI.IDOPERACAO = EA.IDOPERACAO
    WHERE
        OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO = 'V'
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.IDOPERACAO <> 1301
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    IDSECAO,
    S.DESCRSECAO,
    CAST(SUM(VALVENDA) AS NUMERIC(15, 2)) AS VENDA_ATUAL,
    CAST(SUM(VALLUCRO) AS NUMERIC(15, 2)) AS LUCRO_ATUAL
FROM
    BASE
    INNER JOIN DBA.SECAO S ON S.IDSECAO = BASE.IDSECAO
GROUP BY
    IDEMPRESA, NOME_EMPRESA, IDSECAO, S.DESCRSECAO
ORDER BY
    IDEMPRESA, S.DESCRSECAO;
