WITH BASE AS (
    SELECT
        PV.IDSUBPRODUTO,
        PV.DESCRICAOPRODUTO,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT, 0) <= 0 AND OI.TIPOMOVIMENTO = 'V'
                THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALVENDA,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT, 0) <= 0 AND OI.TIPOMOVIMENTO = 'V'
                THEN COALESCE(EA.VALLUCRO, 0) * EA.QTDPRODUTO
            ELSE 0
        END AS VALLUCRO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = EA.IDSUBPRODUTO
        INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
            ON NES.IDEMPRESA = EA.IDEMPRESA
            AND NES.IDPLANILHA = EA.IDPLANILHA
            AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    WHERE
        OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO = 'V'
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.IDOPERACAO <> 1301
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND {{ECOMMERCE}}
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
        AND UPPER(PV.FABRICANTE) = UPPER(?)
)
SELECT
    IDSUBPRODUTO,
    DESCRICAOPRODUTO,
    CAST(SUM(VALVENDA) AS NUMERIC(15, 2)) AS VENDA,
    CAST(SUM(VALLUCRO) AS NUMERIC(15, 2)) AS LUCRO
FROM
    BASE
GROUP BY
    IDSUBPRODUTO, DESCRICAOPRODUTO
ORDER BY
    VENDA DESC;
